version: 2
sources:
  - name: retail
    database: retail_insights_dw
    schema: dbo
    tables:
      - name: Sales
        description: "Raw sales transactions including promotion codes"
        columns:
          - name: SaleID
            tests:
              - not_null
              - unique
          - name: CustomerID
            tests:
              - not_null
          - name: ProductID
            tests:
              - not_null
