retailinsights:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: x6eps4xrq2xudenlfv6naeo3i4-fjpdrtgui7gungssa75taevzhm.daily-datawarehouse.fabric.microsoft.com
      port: 1433
      database: retail_insights_dw
      schema: dbo
      authentication: CLI